Add e2e tests (#30)
* Fix the PodDisruptionBudget `apiVersion`

`make extension-up` fails with:
```
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: resource mapping not found for name: "gardener-extension-registry-cache-admission" namespace: "garden" from "": no matches for kind "PodDisruptionBudget" in version "policy/v1beta1"
```

* Drop unused client from the Shoot validator

* Prefix the server in `hosts.toml` with `https://`

It seems to work also without the `https://` prefix but to be aligned with the upstream docs/examples (ref https://github.com/containerd/containerd/blob/main/docs/hosts.md) and provider-local (ref https://github.com/gardener/gardener/blob/v1.77.0/pkg/provider-local/webhook/controlplane/ensurer.go#L167-L174) I decided to add the prefix for the registry-cache as well.

* Add e2e tests